apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-10-09T22-55-05Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key : "MINIO_ACCESS_KEY"
              name: "minio-creds"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key : "MINIO_SECRET_KEY"
              name: "minio-creds"
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
          - name: minio-storage
            mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-storage
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    service: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      port:  9000
  type: ClusterIP      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
